# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'activerecord', '~> 5.2.3'
gem 'activesupport', '~> 5.2.3'
gem 'factory_bot', '~> 4.8'
gem 'pg', '~> 1.1'
gem 'rake', '~> 12.3.2'
gem 'rspec', '~> 3.10.0'
